language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install coconut
  - pip install autopep8

script:
  - coconut --version
  - coconut src build --strict --debug 2 --autopep8
  - python build/main.py -tt

notifications:
  email: false
